create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'Usuario',
  email text not null,
  currency text not null default 'DOP',
  budget numeric not null default 0,
  credit_due_in_days integer not null default 0,
  possible_savings numeric not null default 0,
  debts numeric not null default 0,
  debt_payment_capacity numeric not null default 0,
  debt_target_months integer not null default 0,
  debt_strategy_mode text not null default 'medium',
  debt_plan_favorites jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.finance_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_key text,
  category text not null,
  name text not null,
  amount numeric not null default 0,
  original_amount numeric not null default 0,
  minimum_payment numeric not null default 0,
  paid_amount numeric not null default 0,
  rate numeric,
  due_date date,
  event_date date,
  status text not null default 'active',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.finance_item_payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  payment_key text,
  item_key text not null,
  category text not null,
  amount numeric not null default 0,
  payment_date date not null,
  note text not null default '',
  previous_amount numeric not null default 0,
  remaining_amount numeric not null default 0,
  payment_type text not null default 'partial',
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.user_profiles add column if not exists debt_payment_capacity numeric not null default 0;
alter table public.user_profiles add column if not exists debt_target_months integer not null default 0;
alter table public.user_profiles add column if not exists debt_strategy_mode text not null default 'medium';
alter table public.user_profiles add column if not exists debt_plan_favorites jsonb not null default '[]'::jsonb;
alter table public.finance_items add column if not exists item_key text;
alter table public.finance_items add column if not exists original_amount numeric not null default 0;
alter table public.finance_items add column if not exists minimum_payment numeric not null default 0;
alter table public.finance_items add column if not exists paid_amount numeric not null default 0;
alter table public.finance_items add column if not exists status text not null default 'active';
alter table public.finance_item_payments add column if not exists payment_key text;

create index if not exists finance_items_user_id_idx on public.finance_items(user_id);
create index if not exists finance_items_category_idx on public.finance_items(category);
drop index if exists public.finance_items_user_item_key_idx;
create unique index if not exists finance_items_user_item_key_idx on public.finance_items(user_id, item_key);
create index if not exists finance_item_payments_user_id_idx on public.finance_item_payments(user_id);
create index if not exists finance_item_payments_item_key_idx on public.finance_item_payments(item_key);
drop index if exists public.finance_item_payments_user_payment_key_idx;
create unique index if not exists finance_item_payments_user_payment_key_idx on public.finance_item_payments(user_id, payment_key);

alter table public.user_profiles enable row level security;
alter table public.finance_items enable row level security;
alter table public.finance_item_payments enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_profiles'
      and policyname = 'Users manage own profile'
  ) then
    create policy "Users manage own profile"
      on public.user_profiles
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'finance_items'
      and policyname = 'Users manage own finance items'
  ) then
    create policy "Users manage own finance items"
      on public.finance_items
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'finance_item_payments'
      and policyname = 'Users manage own finance payments'
  ) then
    create policy "Users manage own finance payments"
      on public.finance_item_payments
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;
