create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'Usuario',
  email text not null,
  currency text not null default 'DOP',
  budget numeric not null default 0,
  credit_due_in_days integer not null default 0,
  possible_savings numeric not null default 0,
  debts numeric not null default 0,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.finance_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  name text not null,
  amount numeric not null default 0,
  rate numeric,
  due_date date,
  event_date date,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists finance_items_user_id_idx on public.finance_items(user_id);
create index if not exists finance_items_category_idx on public.finance_items(category);

alter table public.user_profiles enable row level security;
alter table public.finance_items enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_profiles'
      and policyname = 'Users manage own profile'
  ) then
    create policy "Users manage own profile"
      on public.user_profiles
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'finance_items'
      and policyname = 'Users manage own finance items'
  ) then
    create policy "Users manage own finance items"
      on public.finance_items
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;
